version: '3.5'

services:

  mongo1:
    image: stutzlab/mongo-replset
    build: .
    environment:
      - INIT_REPL_NODES=mongo1,mongo2,mongo3
      - SHARED_KEY_SECRET=mongo_sharedkey
      - ROOT_PASSWORD_SECRET=root_password
    secrets:
      - mongo_sharedkey
      - root_password
    ports:
      - 27017:27017
    volumes:
      - mongo1:/data

  mongo2:
    image: stutzlab/mongo-replset
    build: .
    environment:
      - SHARED_KEY_SECRET=mongo_sharedkey
      - ROOT_PASSWORD_SECRET=root_password
    ports:
      - 27018:27017
    secrets:
      - mongo_sharedkey
      - root_password
    volumes:
      - mongo2:/data

  mongo3:
    image: stutzlab/mongo-replset
    build: .
    environment:
      - SHARED_KEY_SECRET=mongo_sharedkey
      - ROOT_PASSWORD_SECRET=root_password
    ports:
      - 27019:27017
    secrets:
      - mongo_sharedkey
      - root_password
    volumes:
      - mongo3:/data

  mongo-express:
    image: mongo-express:0.54.0
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_SERVER=mongo1,mongo2,mongo3
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD_FILE=/run/secrets/root_password
      # - ME_CONFIG_BASICAUTH_USERNAME=admin
      # - ME_CONFIG_BASICAUTH_PASSWORD=123123
    restart: always
    secrets:
      - root_password
    ports:
      - 8081:8081

secrets:
  root_password:
    file: ./sample_password
  mongo_sharedkey:
    file: ./sample_sharedkey

volumes:
  mongo1:
  mongo2:
  mongo3:
